IF
  Heard("Sirine",1)
  Allegiance(Myself,NEUTRAL)
THEN
  RESPONSE #100
    Enemy()
END

IF
  NumTimesTalkedTo(0)
THEN
  RESPONSE #100
    Dialogue([PC])
    SetGlobalTimer("Sil","GLOBAL",10)
END

IF
  NumTimesTalkedTo(1)
  Allegiance(Myself,NEUTRAL)
  GlobalTimerExpired("Sil","GLOBAL")
THEN
  RESPONSE #100
    Dialogue([PC])
END

IF
  AttackedBy([GOODCUTOFF],DEFAULT)
  Allegiance(Myself,NEUTRAL)
THEN
  RESPONSE #100
    Shout(1)
    Enemy()
END


